export const site = {
  name: "汐间", nickname: "omiki1", wordmark: "BETWEEN TIDES",
  description: "在代码、音乐和世界之间，记录一些没有答案的问题。",
  role: "Developer · Curious mind", location: "Somewhere on Earth",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  avatar: "/avatar.jpg",
  hero: { image: "", greeting: "Hi, I'm", headline: "让好奇心，", emphasis: "慢慢发生。", english: "Code, create & get a little lost." },
  email: "", github: "https://github.com/omiki1",
  bilibili: "https://space.bilibili.com/41883170",
  socials: [
    { label: "GitHub", url: "https://github.com/omiki1" },
    { label: "哔哩哔哩", url: "https://space.bilibili.com/41883170" },
  ] as { label: string; url: string }[],
  nav: [
    {label:"Home",href:"/"},
    {label:"Blog",href:"/blog/"},
    {label:"Archive",href:"/archive/"},
    {label:"Categories",href:"/categories/"},
    {label:"Tags",href:"/tags/"},
    {label:"Projects",href:"/projects/"},
    {label:"相册",href:"/gallery/"},
    {label:"追番",href:"/anime/"},
    {label:"Notes",href:"/notes/"},

    {label:"About",href:"/about/"},
  ],
  seo: { title: "汐间 — omiki1 的数字花园", keywords: ["个人博客", "omiki1", "数字花园", "前端", "AI", "星空", "潮汐", "梦幻", "追番"] },
  music: [
    { title: "Moonlit Current", artist: "Between Tides · 原创环境音", src: "/audio/moonlit-current.wav", cover: "/gallery/deep-tide.webp" },
    { title: "A Quiet Orbit", artist: "Between Tides · 原创环境音", src: "/audio/quiet-orbit.wav", cover: "/gallery/bubble-dream.webp" },
  ],
  pagination: { postsPerPage: 12 },
  now: { learning: "医学 RAG 与 Agent 编排", building: "MediAtlas 证据工作台", activity: "给好奇心留一点空间", updated: "2026.09.16" },
  copyright: "本站为个人非商业的数字花园，与任何游戏或商业公司无关联。鸣潮 / Wuthering Waves 及相关角色版权归 Kuro Games 所有。",
  characterTheme: { name: "DENIA", chinese: "达妮娅", subtitle: "A QUIET RESONANCE", quotes: ["在潮汐之间，留住一点微光。", "让没有答案的问题，漂浮一会儿。", "星光很远，好奇心很近。", "不要看，不要听，不要记在心里。"] },
};
